#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
# Icons from Silk Icon Set
# Mark James
# http://www.famfamfam.com/lab/icons/silk/
from extern.embeddedimage import PyEmbeddedImage

Brick_Add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuJJ"
    "REFUOI11kk9oHGUYxn/f7Eyy+TO7O4lskibxoIQosq3CWkor8RBWBEUPi4GCGPTgodCTl9CL"
    "t9KL10IiWPCQ7pIsUgiCQhCCCBb/ZCQhTXZJt8aUTUgyO91uMs7s932eGuxaf8eXh+d53pdX"
    "8AxWVlau1+v1jzzPOwPgOM7DVCr19cTExLVn6Z+iVCqli8ViqNsoFovh/Pz8mXa9eJLo+/5l"
    "z/OeB4xkMsnY2Bjj4+NordnY2GB7exvf9wGU4zh/JpPJ26eNCoVC8O+0arWqFxcXteu62nVd"
    "vbCwoKvV6lONCoVCABArlUq3TNPMaq3p7+9Ha83m5iatVotqtcre3h6JRAIpJUNDQyilWF9f"
    "x/d9M5fLjZtKqQ8zmQzNZhPXdYnFYuzu7pLP59tvQ3d3N1EU0Ww2SaVSHB4efmAAzeHhYUZG"
    "Rkgmk9i2TTqdplwuo5RCKUW5XGZgYICOjg48zyMMQxzHQWvdNLXWAMTjcSzLotFoYFkWvu+z"
    "trYGQBRFHB0dEQQBlmUBoLVGa42plDodKKXo6upidHSU4+NjlFIcHBxwcnKCbduYpokQAikl"
    "UkqUUphSyi7DMNBaE0URUkqiKEIIgVKKVqtFZ2cn9/Z/5d7+bzwOHhH8fUJm+ALdaiAey+fz"
    "b/q+/0JPTw+9vb1IKQnD8HT/RqPBWu1n9sU6l7LnmXz9bQJrn7sPvuOv2sOaYVnWOzs7O58u"
    "Ly9XVldXEUKQSCQwTRMAKSW/PPiBV186hzQk54ZySBFxIXORiu8+Z0xNTYXT09NfGoZxqVKp"
    "XF9aWqpvbW1h2zZ9fX04jsPBoz0s0ct7L18F4LPJOV5Mn0Ug4qL9t+fm5l4BrmmtL2ezWVGv"
    "1/n8zie8/+4kLRQzuVvc+P5j4rFObn9zJ/iPwRNmZ2ffUkrNKKU6vr3/1W58sDl18ewbjA2+"
    "Rrn2Oz/98SM79/0v/tegnfNXBm8gxBUBtoYGWt+8e7M28w+rNJghLvXdJQAAAABJRU5ErkJg"
    "gg==")
getBrick_AddData = Brick_Add.GetData
getBrick_AddImage = Brick_Add.GetImage
getBrick_AddBitmap = Brick_Add.GetBitmap

#----------------------------------------------------------------------
Brick_Bricks = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAr5J"
    "REFUOI2Vk89rHGUYxz/7zsz+KpvZcXFDupuKxXQrEgXRg5fgJRT1GDwoUkQ0GA8KHvsH9N5T"
    "IQcLQeIuyYrgJVhDa7DC3jIkS0g3idOGbRvtZna6nWSZd+d9PXVpQ0H6OT48z/N9fiZ4Dmtr"
    "a5e73e5F3/dPAziOcy+fzy9MTU1dep7/M9Tr9WKtVov0CWq1WrS4uHj6pH/iiWIQBJ/4vn8G"
    "ELZtMzExQaVSQWvN1tYWe3t7BEEAoBzHuWvb9k/DiqrVav9pNc/z9PLysnZdV7uuq5eWlrTn"
    "ec9UVK1W+wBGvV6/ZprmO1prCoUCWmu2t7cZDAZ4nsfBwQEjIyPEcczY2BhKKZrNJkEQmNPT"
    "0xVTKfXZ5OQkYRjiui6GYdBut5mZmTk5G7LZLFJKwjAkn8/T6XQ+FkBYKpUol8vYtk0ul6NY"
    "LNJqtVBKoZSi1WoxOjpKMpnE932iKMJxHLTWoam1BiCdTmNZFr1eD8uyCIKAzc1NAKSUHB4e"
    "0u/3sSwLAK01WmtMpdTQoJQik8kwPj7O0dERsttF31yleLtFScV0zr+O/+ZbxOkMcRyjlELE"
    "cZwRQiCEQEpJFEVIKTmWkgcrP/KqSCFSSURuhPFuj8xffwxbU0qlBbDWaDQIgoBsNothGFy9"
    "cYXf7v/Cw8f3SJ07j/VSARX49B/scyqTRQjB7u4uSqmGsCzro/39/dnV1dWd9fV1EokEfx/v"
    "8Hb5XcLKWfxfl0naeUw5YPDoX36PX2ZjY+NOp9P5NplMfpB4sqaFhYWilPI7rfU3N+VK/ov3"
    "v8I/7vDzrTt8Hpj881jSeOU9TmVTnDlyy3Nzc+3hKT/N/Pz8G8Cl3aj1aa6cYuN2mq8//JKd"
    "9kP+XL+LYRn88P2FYZw4mWB2drZ5PX/94lnrtQuF+6UbFV3cXLnVJAE6RtDzH/3vQ74Q/wH5"
    "/YjwPclljgAAAABJRU5ErkJggg==")
getBrick_BricksData = Brick_Bricks.GetData
getBrick_BricksImage = Brick_Bricks.GetImage
getBrick_BricksBitmap = Brick_Bricks.GetBitmap

#----------------------------------------------------------------------
Tag_Blue = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAihJ"
    "REFUOI2NkM1LW1EQR8+9+epru7CEZ4x5qVghpSJKsxKzKqUUXHTpqov+Z4UuhUAtGJBAWgIN"
    "uLBFgljl+Vo1EUxiFOJHNHlzuyimWjX0BwMXhnPuzKi1tTVjjEFEMMZw9a2UGkyn03X6pVwu"
    "G9/3b1SlUjErKyumWCza/XhtjAGgWq2yurrK7u4uAPF4HNu2sSyr1k+iRQSAer1OOp1W+/v7"
    "305PTxEREokEtm0TCoXulPQE0WiU5eXlcxGxg8EgB234sgfJZJJYLIZS6lZJ8HKFZDKJ4zjh"
    "TqeTbEmYD67i3FcYI7wYGUFEqFQqtVwuNzg7O1u/OsFZs9kEQEQ46gZ5v6F4GFLELPh+oPlc"
    "hdHRUYaHh4lEIrVcLtebRPu+/9p13bNGo0EgEKDRhgtRaCCoYSDyVzI2NobjOAQCgZ5EAZRK"
    "pUy3282nUinLtm02DoVP25qBe5qwBt9Asw3Po8JLBzY3N/E8j5OTk0ENMDMz8xV4tb6+flar"
    "1Xj6SPNmRDhqCxfy55eQhnL9AjGgtb6s++rqRQuFQsb3/fz4+Lg1NDTExqHwcVsT1poHusPb"
    "lGFv5xee59FqtZ7Mzc39vCYAWFpayhhj8hMTE1Y8HufHoVDc07x7Bjueew3u3eDfLC4uZowx"
    "+cnJSSuRSADgui5bW1scHx/34DsFAAsLC9NAYWpqymq323iedwPuKwDIZrPTQMGyLOs2+L+S"
    "zWan5+fnH9/V/w2LODSct0nVfgAAAABJRU5ErkJggg==")
getTag_BlueData = Tag_Blue.GetData
getTag_BlueImage = Tag_Blue.GetImage
getTag_BlueBitmap = Tag_Blue.GetBitmap

#----------------------------------------------------------------------
Tag_Green = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlBJ"
    "REFUOI2NkUtrE2EUhp+Z3JwWrBAnbXNRYrGLIAlkVRoFNyJk40IoLv0L/gLXLvwHIi4EIZBF"
    "hKSthSxiLRRJIZQ2tE3HSyetTWKqNFeT+T5XDZW0wQMHDpzzPuembG1tSSklQgiklJyPFUXx"
    "RKPRKqNsc3NTWpY15KZpynw+L3O5nD5Kr0opASiXyxQKBQ4ODgCYnp5G13U0TauMgqhCCACq"
    "1SrRaFQ5Pj7eaLVaCCHw+Xzouo7D4bgUMgC43W7W19e7QgjdbrdTb/xgdfs9gUCAyclJFEW5"
    "EGI/WyEQCOD3+529Xi/Q+HPCu9WXdHttJJJ7oUcIITBNs5LJZDzxeLx6foJ2vV4HQAjB73aN"
    "t7kXjF+5iuean8LXHB+3UwSDQbxeLy6Xq5LJZAaTqJZlPSyVSu1arYbNZqPeOKLX76AqKnbV"
    "wcT49QFkZmYGv9+PzWYbQBSAtbW1WL/fX5mdndV0XWfvsEBm4w3Xxt047C4s0eekUSF88y73"
    "7zxmd3cXwzBoNpseFWB+fv4T8KBYLLYrlQq3vRHi0af8av6k1++iKCoOu5Ptb58R0kJV1TMf"
    "U85fNJvNxizLWgmFQtrU1BR7hwXS+dc47E7GnBM8iT2jbB5hGAanp6e3FhYWvgz9dXl5Oba0"
    "tNQyTVNaliWL3/Py1Yfnst1tyZ2dHbm4uCgTiUTwrF4ZIgDpdDompVwJh8Oaz+cDoFQqsb+/"
    "T6PR+KfzhQCAVCo1B2QjkYjW6XQwDGNIPBIAkEwm54CspmnaReL/smQyOZdIJG5clv8Ly4ZK"
    "eEm+RpsAAAAASUVORK5CYII=")
getTag_GreenData = Tag_Green.GetData
getTag_GreenImage = Tag_Green.GetImage
getTag_GreenBitmap = Tag_Green.GetBitmap

#----------------------------------------------------------------------
Tag_Red = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAixJ"
    "REFUOI2NkN9Lk1EYxz/n/aG8GijIO53bChO9GDJjV+KI6iKC0bUU0T8XRSDswmgvyGDQUsEL"
    "oyFLmq9voVvgpitx/pznnC7EoamjLzxw4PD58H0eUSqVtNYapRRaay6/hRChZDJZp1NWV1e1"
    "lPLaVCoVvbKyoguFgtuJN7TWAFSrVYrFIltbWwCEw2Fc18VxnFoniaGUAqBer5NMJsX29vaX"
    "w8NDlFJEIhFc18W27VslbcHAwADLy8snSinXsixo7CIXCsRiMQYHBxFC3CixLlaIxWJEo9Gu"
    "VqsVs5tN1Pt3cHKK1Jp7Dx+hlKJSqdQ8zwul0+n65QZHjUYDAKUU1t4e6u0bRO8dRCgExa/I"
    "z58YGRlheHiY7u7umud57SaGlPKZ7/tHOzs7mKaJbuxC6xQMAywL0dffloyOjhKNRjFNsy0R"
    "AEtLS6mzs7Pc+Pi447oucn0d7X3E6O8DuwukRP9uQOIB5uMnlMtlgiDg4OAgZABMT08vAk/X"
    "1taOarUa5tgYIv0c9WfvvI0QYHdx8q0ESmEYxsX0iMsXzefzKSllLh6PO0NDQ+dNsh8Qtk2r"
    "pxfrxUt+Vn8RBAH7+/v3Z2ZmflwRAMzPz6e01rmJiQknHA4jy9/RiwtYr17jb25egds3+DfZ"
    "bDaltc4lEgknEokA4Ps+GxsbNJvNNnyrAGBubm4KyE9OTjrHx8cEQXAN7igAyGQyU0DecRzn"
    "Jvi/kslkpmZnZ+/e9v8XZxo6vzFHBpoAAAAASUVORK5CYII=")
getTag_RedData = Tag_Red.GetData
getTag_RedImage = Tag_Red.GetImage
getTag_RedBitmap = Tag_Red.GetBitmap
