#!/usr/bin/env python

import sys, os
import wx.tools

# Editra needs its src package to be on the sys.path for plugins and
# such to work right, so put it there before we do the first import of
# any Editra package or module.
sys.path.insert(0, os.path.join(os.path.dirname(wx.tools.__file__),
                                'Editra', 'src'))

import Editra
Editra.Main()
