#!/bin/bash
#----------------------------------------------------------------------

set -o errexit

host=$1
pyver=$2
port=$3

#user=root
user=robind

if [ $skiposx != yes ]; then
    # test if the target machine is online
    if ping -q -c1 -w1 $host > /dev/null; then
	echo "The $host machine is online, OSX build continuing..."
    else
	echo "The $host machine is **OFFLINE**, skipping the OSX build."
	exit 0
    fi

    echo "Copying source files and build script..."
#    ssh $user@$host "mkdir -p $OSX_BUILD && rm -rf $OSX_BUILD/* || true"
    
    scp $STAGING_DIR/wxPython-src-$VERSION.tar.bz2 \
	$STAGING_DIR/wxPython-docs-$VERSION.tar.bz2 \
	$STAGING_DIR/wxPython-demo-$VERSION.tar.bz2 \
	distrib/all/do-build-osx \
	$user@$host:$OSX_BUILD

    echo "Running build script on $host..."
    wxdir=$OSX_BUILD/wxPython-src-$VERSION
    cmd=./do-build-osx
    ssh $user@$host "cd $OSX_BUILD && $cmd $wxdir $OSX_BUILD $skipclean $VERSION $pyver $port && rm $cmd"
    
    echo "Fetching the results..."
    scp "$user@$host:$OSX_BUILD/wxPython*-osx*"  $STAGING_DIR
    ssh $user@$host "rm $OSX_BUILD/wxPython*-osx*"

    echo "Done!"
    sleep 1
fi

