#!/bin/bash
#----------------------------------------------------------------------

set -o errexit
#set -o xtrace

host=$1
chRootRoot=$2
chRootName=$3


if [ $buildansi = yes ]; then
    CHARTYPE=both
else
    CHARTYPE=unicode
fi


function TestOnline {
    local host=$1
    local message=$2

    if ping -q -c1 -w1 $host > /dev/null; then
	return 0
    else
	return 1
    fi
}

#user=root
user=robind

if [ $skipdeb != yes ]; then
    # We use a chroot environment on the build machine for the debian
    # builds, so this build is pretty simple.  Just copy the tarball
    # and a build script to the build machine, and then run
    # do-build-deb in the chroot.

    if TestOnline $host; then
    
	echo "The $host machine is online, build continuing..."

	echo "Copying source files and build script..."
	ssh $user@$host "mkdir -p $chRootRoot/$LINUX_BUILD && rm -rf $chRootRoot/$LINUX_BUILD/*"
	scp $STAGING_DIR/wxwidgets*.orig.tar.gz distrib/all/do-build-deb \
            $user@$host:$chRootRoot/$LINUX_BUILD
    
	ssh $user@$host "dchroot --chroot $chRootName --directory $LINUX_BUILD \"./do-build-deb $VERSION $VER2 $CHARTYPE\""

	echo "Fetching the results..."
	mkdir -p $STAGING_DIR/$chRootName
	ssh $user@$host "rm $chRootRoot/$LINUX_BUILD/do-build-deb"
	scp "$user@$host:$chRootRoot/$LINUX_BUILD/*"  $STAGING_DIR/$chRootName
	ssh $user@$host "rm $chRootRoot/$LINUX_BUILD/*"
	echo "Done!"
    else
	echo "The $host machine is **OFFLINE**, skipping the binary DEB build."
	exit 0
    fi
fi

